version: '3.4'
services:
  client:
    container_name: javelin_client
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000
    networks: 
      - frontend

  server:
    container_name: javelin_server
    build: 
      context: ./server
    depends_on:
      - database
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 5000:5000
    networks: 
      - backend
    
  database:
    image: mongo:4.4.2
    container_name: javelin_database
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=javelin
    networks: 
      - backend
      
volumes:
  mongo-data:

networks:
  frontend:
  backend: